### ISSUE TITLE
improve the documentation of the headway/frequency functions

### ISSUE THREAD

**Issue by angela-li** [r-transit/tidytransit#10]

**Comment by tbuckl** [comment]
@angela-li not sure if this will help, but i think service_id selection is going to be a key part of making frequency calculation more robust: https://github.com/r-transit/tidytransit/issues/18

**Comment by tbuckl** [comment]
hi @angela-li i hope all is well. i had a good chat with a guy who runs MTC's regional GTFS program about frequency calculations. he pointed out all the difficulties with calculating frequency specifically for any given route. in some ways it makes any kind of consistent calculation difficult. i still think the calculations here might be useful to some users as a rough heuristic. but it might also be nice to include some kind of estimate for standard error of the estimate, based on the number of patterns, or missing values in the patterns or something. any thoughts? no rush on this just thought i should make a note of it here.

**Comment by ashley-gentles** [comment]
@angela-li Hi Angela! I'm thinking of using tidytransit for a project, specifically for the frequency and headway calculations. Can you tell me about some of the ways that the frequency functions fail? I'd like to have a better understanding of how things might go awry. Thanks!

**Comment by tbuckl** [comment]
Hi @ashley-gentles thanks for asking about this. @angela-li has provided a lot of great insight into the design of this package. So I look forward to hearing her thoughts here. 

Also, understanding the quality of the frequency calculations and how they work, is one of the reasons I wanted to work on this project. I thought it might make a lot of sense for quality of service measures to be accessible to a lot of analysts and open source. 

I developed the service frequency functions in here with colleagues from a government agency that was tasked with responding rapidly to request from policymakers about service quality. 

While I can't speak as intelligently as many others about the different ways to calculate service quality, I'd be happy to think about how we can do the following:

1) enumerate methods for calculating service quality from GTFS
2) incorporate new methods to the calculations here (potentially as new argument, etc)

Let me know if any of that might be of interest to you. We could collaborate on (1) as a markdown document, or in [the wiki](https://github.com/r-transit/tidytransit/wiki)

**Comment by tbuckl** [comment]
@ashley-gentles @angela-li i updated the issue to be something more discrete that will get us closer to the goal. we can open other issues as they come up. i think this is still a bit exploratory and could result in a lot of new issues.

**Comment by tbuckl** [comment]
here's a relevant study: http://docs.trb.org/prp/15-6045.pdf

**Comment by tbuckl** [comment]
hi @ashley-gentles sorry, i think when i said service "quality" what i meant was actually just headways or frequencies. 

thats a really cool idea about allowing users to review the quality of the headway or frequency estimate through an interactive app! 

i have not played around with shiny much, but that might be a good place to start?

what i had in mind with this issue is: there are probably a bunch of standard definitions that people trained in civil engineering have for headways/frequencies. that would be a different way to approach the problem than yours. 

i think your app-based feedback might be close to the way someone like [jarret walker](https://humantransit.org/) would approach this.

**Comment by tbuckl** [comment]
@ashley-gentles i'll be at [transportation camp tomorrow in DC](http://transportationcamp.org/) and will bring up your idea and point people to this issue. or feel free to create a new issue if you'd like to.

**Comment by tbuckl** [comment]
@ashley-gentles you might also want to create your own repository to work out the app. you could import tidytransit if its useful to you.

**Comment by ashley-gentles** [comment]
Hi @tbuckl, thanks for your help! Would you mind if I contact you more directly, by email?

**Comment by tbuckl** [comment]
@ashley-gentles sure, my email is my name: tom
at, followed by my github handle
followed by .com

**Comment by tbuckl** [comment]
@polettif has already started this here: https://github.com/r-transit/tidytransit/pull/45

the goal would be to improve the example here: https://github.com/r-transit/tidytransit/blob/master/R/frequencies.R#L15-L19

and here: https://github.com/r-transit/tidytransit/blob/master/R/frequencies.R#L95-L99

so that users can clearly see how "headways" are being calculated by these particular functions.

**Comment by tbuckl** [comment]
closing this out for now.
