### ISSUE TITLE
add get_route_frequency() and document deprecation

### ISSUE THREAD

**Issue by 3ChordP** [r-transit/tidytransit#166]
Function get_route_frequency() was available in 0.7.3, but I'm not seeing it in 1.0.0.

**Comment by tbuckl** [comment]
@3ChordP yes, we've deprecated that function. @polettif recently made some major changes to how GTFS data are read by importing gtfsio. while doing so, he developed some questions about route_frequency that i was not able to answer in time, yet i did not want to block his release, so we deprecated it. we could add it back in. do you have a specific use case you can share that would help us understand the priority of adding it back in?

you can still install the old package version like so:

https://support.rstudio.com/hc/en-us/articles/219949047-Installing-older-versions-of-packages

**Comment by tbuckl** [comment]
closing this issue due to lack of actionable feedback

**Comment by michaelgaunt404** [comment]
@tbuckl Hi, came back to this package after not using it for a couple of months and saw that this function is deprecated. 
I used this package a lot to perform transit simulations and really appreciated that function to provide headway statistics that I could use in my sims. 

Any reason why running the older version of the package may or may not be a good idea?
If I grabbed that function from the older release version would it still be compatible with the most recent release of the package ?

**Comment by polettif** [comment]
I'll chime in on what lead to the function being removed with v1.0 (more on this in [#108](https://github.com/r-transit/tidytransit/issues/108#issuecomment-535418406)): Basically, `get_route_frequency` and `get_stop_frequency` use(d) default parameters and built-in assumptions to calculate frequencies which weren't really documented properly or changeable. For example, `mean_headway` was rather a "mean of every stop's mean_headway". Also IMO using "headway" was a bit misleading since the whole analysis time (6am-10pm) was used instead of actual headways. 

I do realize that rewriting the function instead of removing it would've been the better approach. However, I still think that such "parameter heavy" analysis is better done on a per use basis instead of a catch-all-function. 

I'd strongly suggest using the current tidytransit version as it's based on [gtfsio](https://github.com/r-transit/gtfsio) and provides much faster feed reading along with other improvements. Simply copying the old functions might work but I think there were some helper functions removed as well. With current tidytransit versions you could use something like this, based on the old version:

``` r
library(tidytransit)
library(dplyr)

gtfs_nyc = read_gtfs(system.file("extdata", "google_transit_nyc_subway.zip", package = "tidytransit"))

# parameters
analysis_date = "2018-10-04"
analysis_start_time = 6*3600 # or hms::as_hms("06:00:00")
analysis_end_time = 22*3600

# Use data from a single date, using service_ids looks easier at first
# but they might not work as expected
g = filter_feed_by_date(gtfs_nyc, analysis_date)

# get number of departures per stop and direction
analysis_duration = analysis_end_time - analysis_start_time
stop_time_trips = g$stop_times %>% 
  inner_join(g$trips, by = "trip_id") %>% 
  filter(departure_time > analysis_start_time & arrival_time <= analysis_end_time)

departures_per_stop = stop_time_trips %>%
  group_by(route_id, direction_id, stop_id, service_id) %>%
  summarise(n_departures = n(), .groups = "drop") %>% 
  mutate(mean_stop_headway = analysis_duration / n_departures)

# replaces get_route_frequency
route_freq = departures_per_stop %>% 
  group_by(route_id) %>%
  summarise(total_departures = sum(n_departures),
            median_headways = round(median(mean_stop_headway)),
            mean_headways = round(mean(mean_stop_headway)),
            st_dev_headways = round(sd(mean_stop_headway),2),
            stop_count = n())

route_freq
#> # A tibble: 29 × 6
#>    route_id total_departures median_headways mean_headways st_dev_headways
#>    <chr>               <int>           <dbl>         <dbl>           <dbl>
#>  1 1                   14559             299           301            8.9 
#>  2 2                   12780             445          3084         8076.  
#>  3 3                    8361             468           469            4.72
#>  4 4                    8374             381          6891        12308.  
#>  5 5                    8199             565          6620        16242.  
#>  6 5X                    580            2880          2880            0   
#>  7 6                   12267             333           394          161.  
#>  8 6X                   3321            1152          1304         1047.  
#>  9 7                    9573             276           266           17.0 
#> 10 7X                   1244            1166          1153          223.  
#> # … with 19 more rows, and 1 more variable: stop_count <int>
```

<sup>Created on 2021-11-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by polettif** [comment]
After some [further digging](https://twitter.com/sharon000/status/1448124541163692040) I realized that while removing the function was necessary for a swift release of v1.0 but we did lose functionality (and a vignette...) in the process. I'll update `get_stop_frequency` and `get_route_frequency` and re-add it to the package.

**Comment by tbuckl** [comment]
agree with @polettif that such parameter-heavy analysis is better handled with a per-instance/feed approach
