### ISSUE TITLE
fix tests and put package back on CRAN

### ISSUE THREAD

**Issue by bpb824** [r-transit/tidytransit#169]
Is anyone working on resolving the unit test failures? I could help but don't want to duplicate work. 

https://cran.r-project.org/web/packages/tidytransit/index.html

**Comment by tbuckl** [comment]
that would be great @bpb824! happy to add you as an author/contributor/maintainer as necessary. can you fork and submit a pull request that would fix? @polettif you mind if we switch over the maintainer to @bpb824 and move me to an author role?

**Comment by polettif** [comment]
The issue has been fixed in [this commit](https://github.com/r-transit/tidytransit/commit/e6176e7ef15817a0bc1a5b3fd5e9974e911d425c) on #168. I wasn't aware of it and encountered it while working on the branch, so I don't recall what the issue was exactly. Are there any other fixes necessary?

The development branch is still failing, so maybe a hotfix to get this back on CRAN is the way to go?

**Comment by polettif** [comment]
> The development branch is still failing, so maybe a hotfix to get this back on CRAN is the way to go?

```
*** arch - i386
Error: Error: package or namespace load failed for 'tidytransit' in library.dynam(lib, package, package.lib):
 DLL 'datatable' not found: maybe not installed for this architecture?
Error: Error: loading failed
```

This seems to be an issue with datatable on [windows-latest (devel)](https://github.com/r-transit/tidytransit/pull/168/checks?check_run_id=3083871838#step:9:111), 3.6 and 4.0 run fine. So I think we could merge #168

**Comment by polettif** [comment]
v1.1 is ready to go. However, there is some (unexpected) additional documentation required, so the CRAN release is still in progress.

**Comment by polettif** [comment]
[v1.1 is on CRAN ](https://cran.r-project.org/package=tidytransit) ✅
