### ISSUE TITLE
Allow encoding parameter to be passed in read_gtfs()

### ISSUE THREAD

**Issue by bartosz-mccormick** [r-transit/tidytransit#190]
Hi! Would it be possible to add the parameter `encoding` to `read_gtfs()` which would then be passed to `gtfsio::import_gtfs()`? By default the value can be `encoding = "unknown"` or `encoding = NULL` to maintain existing functionality.

The current implementation leaves this parameter unspecified:

![image](https://user-images.githubusercontent.com/53804836/204334787-8f45833a-d051-4d81-b1c9-d7d9921d20c0.png)

![image](https://user-images.githubusercontent.com/53804836/204333798-8118f461-35be-4d3b-80c7-7b5fa0d49c40.png)

For instance, this would allow the issue below to be resolved!

![image](https://user-images.githubusercontent.com/53804836/204329767-45d18887-bf45-4911-9bdd-2a7a2c825388.png)

**Comment by mpadge** [comment]
But note that [the official reference](https://developers.google.com/transit/gtfs/reference#file_requirements) states that:

> Files should be encoded in UTF-8 to support all Unicode characters

(Stuff like the above example of mucked up place names is generally a locale issue, caused by local OS settings, not by this or other packages. If "encoding" were to be set, I'd suggest it should be done only to internally hard-code UTF-8, and definitely *not* to allow users to modify encodings.)

**Comment by polettif** [comment]
Ah right, thanks @mpadge So the question should rather be, why gtfsio uses an encoding parameter? I'd guess because encoding is finicky and setting an encoding parameter could be an easy workaround, is that in the right area @dhersz?

For tidytransit, I'd still suggest using `...` to allow users to pass arguments to `import_gtfs`.

**Comment by dhersz** [comment]
Hi. Sorry for the late reply, I had been quite busy the last few months and weeks.

Yes @polettif, that's exactly why the `encoding` parameter was added. I also had some problems with station and route names being messed up when not explicitly setting the encoding, and I thought that using `data.table::fread()` `encoding` parameter was the correct way forward. At the time I wondered whether defaulting to `"unknown"` (`fread()`'s default) or `"UTF-8"` (due to the specification) would be correct, but I ended up using data.table's default.

@mpadge `fread()` documentation reads:

> `encoding` - default is `"unknown"`. Other possible options are `"UTF-8"` and `"Latin-1"`. Note: it is not used to re-encode the input, rather enables handling of encoded strings in their native encoding.

So, if my interpretation is correct, the parameter is not used to modify encodings, but to correctly interpret input that for some reason (perhaps a locale issue?) happened to be incorrectly encoded. Is that correct? If so, how do you recommend going forward?
