### ISSUE TITLE
Problem reading sample data from {gtfstools}

### ISSUE THREAD

**Issue by dhersz** [r-transit/tidytransit#192]
I've been facing some problem trying to read a sample feed included in {gtfstools}, not sure why. Gonna investigate a bit further, but it'd be interesting to know if you can reproduce this behaviour locally:

``` r
library(tidytransit)

data_path <- system.file("extdata/spo_gtfs.zip", package = "gtfstools")

gtfs <- read_gtfs(data_path)
#> Error in reshapeLong(data, idvar = idvar, timevar = timevar, varying = varying, : 'idvar' must uniquely identify records
```

<sup>Created on 2022-12-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by dhersz** [comment]
Ok, found the problem. Most specifically, the error is thrown by `set_dates_services()`:

``` r
data_path <- system.file("extdata/spo_gtfs.zip", package = "gtfstools")

gtfs <- gtfsio::import_gtfs(data_path)
gtfs$. <- list()
gtfs <- tidytransit:::convert_times_to_hms(gtfs)
gtfs <- tidytransit:::convert_dates(gtfs)

tidytransit:::set_dates_services(gtfs)
#> Error in reshapeLong(data, idvar = idvar, timevar = timevar, varying = varying, : 'idvar' must uniquely identify records
```

<sup>Created on 2022-12-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

This happens because the feed I'm trying to read has duplicate `calendar` entries:

```r
gtfs$calendar[]
#>     service_id monday tuesday wednesday thursday friday saturday sunday
#>  1:        USD      1       1         1        1      1        1      1
#>  2:        U__      1       1         1        1      1        0      0
#>  3:        US_      1       1         1        1      1        1      0
#>  4:        _SD      0       0         0        0      0        1      1
#>  5:        __D      0       0         0        0      0        0      1
#>  6:        _S_      0       0         0        0      0        1      0
#>  7:        USD      1       1         1        1      1        1      1
#>  8:        U__      1       1         1        1      1        0      0
#>  9:        US_      1       1         1        1      1        1      0
#> 10:        _SD      0       0         0        0      0        1      1
#> 11:        __D      0       0         0        0      0        0      1
#> 12:        _S_      0       0         0        0      0        1      0
#>     start_date   end_date
#>  1: 2008-01-01 2020-05-01
#>  2: 2008-01-01 2020-05-01
#>  3: 2008-01-01 2020-05-01
#>  4: 2008-01-01 2020-05-01
#>  5: 2008-01-01 2020-05-01
#>  6: 2008-01-01 2020-05-01
#>  7: 2008-01-01 2020-05-01
#>  8: 2008-01-01 2020-05-01
#>  9: 2008-01-01 2020-05-01
#> 10: 2008-01-01 2020-05-01
#> 11: 2008-01-01 2020-05-01
#> 12: 2008-01-01 2020-05-01
```

Once I fix this, the problem is solved:

```r
gtfs$calendar <- unique(gtfs$calendar)

tidytransit:::set_dates_services(gtfs) |> class()
#> [1] "gtfs" "list"
```

Any ideas how to follow from here? Remove duplicate calendar entries before applying the function? Improve error message to clue the user on what might be the problem?

**Comment by polettif** [comment]
Interesting issue, handling non-standard feeds in a "standard" way is always a bit tricky. 
In this case, `unique(gtfs$calendar)` might work but it's also possible that there are multiple rows with the same id but different values in monday-friday which then leads to the same error.

My prefered way to handle this is usually errors. However, throwing an error isn't really helpful because users can't fix the issue within R as you can't even load the feed. So I'd suggest this:

- Check if all `service_ids` are unique within `calendar`
- if that's not the case: don't run `set_dates_services` and issue a warning describing the issue. BTW: It might also be useful to check for unique ids in all tables.
- The object returned by `read_gtfs` (in case of a warning) is not _yet_ a tidygtfs object

Then we move all these "tidytransit preparation functions" into a new exported function like `as_tidygtfs` which might also come in handy for our [other discussions](https://github.com/r-transit/gtfsio/discussions/29):

https://github.com/r-transit/tidytransit/blob/3203e9546ab9a05394637fccca8fbdb413ab660a/R/io.R#L33-L36

After fixing a feed (in this case: `gtfs$calendar <- unique(gtfs$calendar)`) you can run `as_tidygtfs` to set dates_services and so on.
