### ISSUE TITLE
A to B routing

### ISSUE THREAD

**Issue by Robinlovelace** [r-transit/tidytransit#32]
Sorry for potentially naive question but can this route from A to B with gtfs data?

Context: @mem48 and I are currently using OpenTripPlanner for this but it has quite a lot of overheads, but is very good for multi-modal routing (perhaps one day that will be possible in R).

**Comment by Robinlovelace** [comment]
Thanks for the quickfire response and useful link. Handy!

**Comment by mpadge** [comment]
This issue is much more difficult than it might at first seem, because there is generally no single way between A and B in public transport systems. This means it is not a typical "routing" problem, and no traditional routing algorithms or approaches can be applied here. A GTFS feed can be used to extract the route followed by a particular service, along with departure times, but whether or not a particular individual will go from A to B via C or via D will depend on a host of unpredictable and ultimately subjective and unknowable factors.

On the other hand, in going from A to B, we as transport analysts are only ever really likely to want to know the shortest possible time this might take. This will depend on the actual time of departure, but there will always be a 1:1 mapping between time of departure and time taken. There will not necessarily be a 1:1 mapping between time of departure and spatial routes, so this can't be sensibly analysed.

I would thus rephrase the problem as that of finding quickest travel time between A and B given a specific departure time from A. This is possible in principle, but faces an additional difficulty. Given a comprehensive set of GTFS feeds, it's totally easy. What we can never know, however, is whether a given set of feeds is comprehensive or not. There may always be other potential routes that are simply not present in a given set of feeds, and so we can't ever really ensure that a result is truly the shortest path. The best we can likely do is just assemble lots of feeds and manually ascertain that they are sufficiently representative for a given location.

Packaging this as an R package is, in my opinion, not likely to be possible because feeds change constantly, and that kind of dynamic system is far better handled in other ways (likely most effectively as a web server). Nevertheless, all very interesting and important stuff to keep in mind ...

**Comment by polettif** [comment]
That's awesome! What's the implemented algorithm, connection scan?

As to how to integrate it: I prefer combining all methods and use cases for gtfs within tidytransit. It's easier for users as they don't need to look up several packages for gtfs and we can re-use the "wrangling methods" you mentioned. On the other hand, issues and development might get a bit clogged so keeping it on a separate repository (on ATFutures oder r-transit) might be prefarable until it's reached a stable build.

**Comment by mpadge** [comment]
Thanks @polettif! I agree with the advantages of having `tidytransit` as a one-stop-shop for GTFS. But acknowledging your other concerns, I'll leave it where it is for now until I've got the API in a more stable state. One of my visions is in terms of a really strong "selling point" for this package: set envvars for your personal home and work stations, and you can just
```
tidytransit::go_home()
```
or
```
tidytransit::go_to_work()
```
And you'll get the full timetable of next available connection. That immediately segues to next issue which is caching. I intend to set up `gtfs-router` to use local caching, particularly because the GTFS data need to be restructured for efficient routing. As you wisely suggest, we don't want to clutter up the issues here too much, but caching is likely to be very important for many GTFS enquiries, so that any and all desired feeds will only need to be accessed once, with subsequent storage and retrieval then automated without the user having to specify anything. Lots of current `tidytransit` functions will likely benefit from this, so you can hopefully develop stuff in the meantime with that endpoint in mind.

---

Oh, and yes, a connection-scan-type algorithm. Somewhat modified, but just a linear scan of timetable in increasing time.

**Comment by polettif** [comment]
Sounds good! I'd say we move discussion over to the gtfsrouter repo until you're ready to implement.

If I may add some design thoughts, I'd love to use gtfsrouter/tidytransit to analyse feeds on an aggregate basis. For example, isochrone/reachability maps or service quality analysis. Mainly things that are done by working on data frames. I'm not sure R is the best environment for single trip planning (as you suggested with `go_home()`). [OpenTripPlanner](https://github.com/opentripplanner/OpenTripPlanner) for example provides this quite extensively, although in Java.

**Comment by mpadge** [comment]
Our future visions seem quite aligned: as stated in the [`gtfsrouter` README](https://github.com/atfutures/gtfs-router), "Among the additional aims of this repo are to quantify the dynamic stability of a GTFS network in time and space, and to identify “weakest nodes” as those where a temporal disruption propogates out to have the greatest effect throughout the broader network."

As for R not being "the best environment for single trip planning" - I would strongly argue that that is simply because such tools have not been previously available. `gtfs-router` is enormously more lightweight than OpenTripPlanner, and will even work offline. I already prefer the simplicity of this interface that I have developed over anything else.

By the way, the new github "Transfer Issue" button could be used to directly transfer this over to `gtfs-router`. I'll grant you access to that repo, and you should be able to do it.

**Comment by polettif** [comment]
> Our future visions seem quite aligned: as stated in the [`gtfsrouter` README](https://github.com/atfutures/gtfs-router), "Among the additional aims of this repo are to quantify the dynamic stability of a GTFS network in time and space, and to identify “weakest nodes” as those where a temporal disruption propogates out to have the greatest effect throughout the broader network."

Nice, I think we're on the same page then.

> As for R not being "the best environment for single trip planning" - I would strongly argue that that is simply because such tools have not been previously available. `gtfs-router` is enormously more lightweight than OpenTripPlanner, and will even work offline. I already prefer the simplicity of this interface that I have developed over anything else.

Sure! Don't get me wrong, the overhead OpenTripPlanner needs makes it hard to work with in a data scienc-y setting, let alone set it up in an quick and easy way (although you can run it offline as a localhost server). It's also really cumbersome to go through several factories and interfaces to even do basic analysis. I guess what I'm trying to say, let's keep it lightweight ;) And using shiny to create user friendly interfaces opens up quite some possibilities. 

> By the way, the new github "Transfer Issue" button could be used to directly transfer this over to `gtfs-router`. I'll grant you access to that repo, and you should be able to do it.

Much appreciated but it seems that you can only transfer issues within an organisation.

**Comment by tbuckl** [comment]
hey @polettif and @mpadge i'm going to rename this as "general discussion around routing packages in r" since we're probably not going to implement routing in here. 

i'd actually prefer to close it if thats ok, since it sounds like this is just a confusing place for it to be in any case (e.g. your discussion of transferring issues). feel free to reopen it if that doesn't make sense.
