### ISSUE TITLE
Reimplement hms frequency tests

### ISSUE THREAD

**Issue by polettif** [r-transit/tidytransit#47]
See #45 and #46

**Comment by mpadge** [comment]
For what it's worth, the current [`gtfsrouter` package](https://github.com/ATFutures/gtfs-router), intended to be integrated in this package via #32, has a bunch of internal C++ routines for parsing and processing GTFS times. These are much faster than `hms` or `lubridate`, because the GTFS formats are strictly hard-coded, allowing for large efficiency gains over standard routines. These can all be directly used once `gtfsrouter` is integrated here.
