### ISSUE TITLE
read non-gtfs-spec column names in parse_gtfs

### ISSUE THREAD

**Issue by polettif** [r-transit/tidytransit#6]
When using the [google sample feed](https://developers.google.com/transit/gtfs/examples/sample-feed.zip), the resulting stop_times_df looks like
```
$stop_times_df
# A tibble: 28 x 9
   trip_id arrival_time departure_time stop_id        stop_sequence stop_headsign pickup_type X8    shape_dist_traveled
   <chr>   <chr>        <chr>          <chr>                  <int> <chr>               <int> <chr>               <dbl>
 1 STBA    6:00:00      6:00:00        STAGECOACH                 1 NA                     NA NA                     NA
 2 STBA    6:20:00      6:20:00        BEATTY_AIRPORT             2 NA                     NA NA                     NA
 3 CITY1   6:00:00      6:00:00        STAGECOACH                 1 NA                     NA NA                     NA
 4 CITY1   6:05:00      6:07:00        NANAA                      2 NA                     NA NA                     NA
 5 CITY1   6:12:00      6:14:00        NADAV                      3 NA                     NA NA                     NA
 6 CITY1   6:19:00      6:21:00        DADAN                      4 NA                     NA NA                     NA
 7 CITY1   6:26:00      6:28:00        EMSI                       5 NA                     NA NA                     NA
 8 CITY2   6:28:00      6:30:00        EMSI                       1 NA                     NA NA                     NA
 9 CITY2   6:35:00      6:37:00        DADAN                      2 NA                     NA NA                     NA
10 CITY2   6:42:00      6:44:00        NADAV                      3 NA                     NA NA                     NA
```

The problem seems to be that the column "drop_off_time" is not a valid column name which is pretty strange for an example feed. Also there are commas missing from line 17 on but that's not the point.

My question is: Why are only required/expected columns read in [import.R#348](https://github.com/r-transit/tidytransit/blob/33c965902fe8a07aea3207b7fd73c620cc526a73/R/import.R#L348)? Why don't we simply read the whole file as a simple csv and check validity afterwards? The column X8 we get isn't really helpful anyways.

**Comment by tbuckl** [comment]
thanks @polettif good point. 

outstanding tasks for getting parse_gtfs into a spot where it handles unspecified column names are:

clean up variable names here:

https://github.com/r-transit/tidytransit/blob/33c965902fe8a07aea3207b7fd73c620cc526a73/R/import.R#L311-L330

there is a vector colnms and a colnames.

define specified types using readr compatible types (e.g. col_double) rather than "d" so that we can pass them in in read_csv.  thats done [here](https://github.com/r-transit/tidytransit/blob/33c965902fe8a07aea3207b7fd73c620cc526a73/R/spec.R#L11)

i started doing some of this on a branch (see the commit above), at the line you mentioned, which is hard to read as is. 

happy to accept PR's on this. probably won't get to it myself.
