### ISSUE TITLE
make it easier for developers to use this package

### ISSUE THREAD

**Issue by angela-li** [r-transit/tidytransit#7]
I think we can find a way to rewrite the functions so that there's a parameter in function calls for `sf=TRUE`. Otherwise, we can just show lat and long in the dataframes that are returned, because that's what's in GTFS data anyway.

Will look into this later.

**Comment by tbuckl** [comment]
from https://github.com/r-transit/trread/issues/5

**Comment by tbuckl** [comment]
renaming because i think in terms of the function arguments, this is going to be handled/merged in https://github.com/r-transit/tidytransit/pull/22 but we still need to slim down the 'sf' work to 'sfc'

**Comment by tbuckl** [comment]
hey @mpadge is this the right issue title for [your question](https://github.com/r-transit/tidytransit/issues/49) about how to manage "merging" this package with other packages?

i think tidytransit ended up being more oriented toward users than developers, partially by the prompting of @angela-li to consider that a user would not want to have to import and think about multiple packages to just do basic mapping and frequency/schedule analysis. 

i think that intuition was right, but as you work on gtfs-router i expect you'll develop better approaches across a number of problems. 

another way to think about this issue is how to deprecate this package gracefully as you advance your work on gtfs-router. could just be managed by having a similar api.

**Comment by tbuckl** [comment]
closing this issue and opening a new one because the top level message doesn't correspond to the issue title and i think we already do whats specified at the top, which is to allow routes to be processed as an option in read_gtfs.
